module.exports = {
  MAX_QUESTIONS: 3,
  MIN_QUESTIONS: 3,
  MAX_FOLLOW_UPS: 2,
  TIME_LIMIT_MINUTES: 45,
  DIFFICULTY: { EASY: 1, MEDIUM: 2, HARD: 3 },
  THRESHOLDS: {
    FOLLOW_UP_SCORE: 50,
    ADVANCE_DIFFICULTY: 80,
    DROP_DIFFICULTY: 40,
  },
};